name: Run tests
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up GoLang
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

